# Generated by Django 4.0.6 on 2022-10-02 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashbookapp', '0021_cashbook_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfield', models.ManyToManyField(blank=True, editable=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
