# Generated by Django 4.0.6 on 2022-10-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0022_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
